name: project1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  fluttertoast: ^8.0.9
  package_info_plus: ^8.0.0
  email_validator: ^2.1.17
  firebase_auth: ^4.20.0
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  auto_route: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0
  flutter_gen: ^5.5.0+1
  flutter_lints: ^3.0.0

flutter_gen:
  output: lib/gen/  
  integrations:
    flutter_svg: true 

flutter:
  assets:
    - assets/images/contact-mail.png  
  uses-material-design: true
