// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF2YZRdtP-EcbFQr2CDNA0v6XeUNeUnHs',
    appId: '1:353247836212:web:02cfad772da02163b53261',
    messagingSenderId: '353247836212',
    projectId: 'contact-fourm-98cf0',
    authDomain: 'contact-fourm-98cf0.firebaseapp.com',
    databaseURL: 'https://contact-fourm-98cf0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'contact-fourm-98cf0.appspot.com',
    measurementId: 'G-FB738LZWQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6K-gRbNIxr3BYkjqxXahSLFHzr7Xb5qY',
    appId: '1:353247836212:android:dfd07c7256e69a67b53261',
    messagingSenderId: '353247836212',
    projectId: 'contact-fourm-98cf0',
    databaseURL: 'https://contact-fourm-98cf0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'contact-fourm-98cf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJoXiWR62oCUlSzburAUSUgvmsSXu1njM',
    appId: '1:353247836212:ios:d084911526a55a8db53261',
    messagingSenderId: '353247836212',
    projectId: 'contact-fourm-98cf0',
    databaseURL: 'https://contact-fourm-98cf0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'contact-fourm-98cf0.appspot.com',
    iosBundleId: 'com.example.project1',
  );
}
